# This file is a template for all of the statistical data to be kept for the game.# The game code will load this file along with a game_data.yaml file.  
# Any items not present in the game_data.yaml file will default to the 
# value specified here.  When game ends or when defaults are restored, 
# game_data will be written and will then contain every item here.

Audits:
  Avg Ball Time: 0:00
  Avg Extra Balls: 0
  Avg Game Time: 0:00
  Avg Score: 0
  Games Played: 0
  Games Started: 0
  Balls Played: 0
ClassicHighScoreData:
- {date: 'Sun Oct  3 17:38:46 2010', inits: OIC, score: 500000}
- {date: 'Sun Oct  3 17:44:49 2010', inits: LIZ, score: 400000}
- {date: 'Sun Oct  3 16:22:47 2010', inits: JCT, score: 300000}
- {date: 'Sun Oct  3 15:04:27 2010', inits: ABI, score: 200000}
- {date: 'Sun Oct  3 22:05:01 2010', inits: EMM, score: 100000}
RiverBankHighScoreData:
- {date: 'Sun Oct  3 22:05:01 2010', inits: OIC, score: 2}
QuickdrawChampHighScoreData:
- {date: 'Sun Oct  3 22:05:01 2010', inits: OIC, score: 2}
ComboChampHighScoreData:
- {date: 'Sun Oct  3 22:05:01 2010', inits: OIC, score: 2}
ShowdownChampHighScoreData:
- {date: 'Sun Oct  3 22:05:01 2010', inits: OIC, score: 2}
AmbushChampHighScoreData:
- {date: 'Sun Oct  3 22:05:01 2010', inits: OIC, score: 2}
